"""Offshore engineering workflows built on UQRA."""

__version__ = "0.1.0a1.dev0"

from offshoresafe.postprocessing import (
    ChannelStatistics,
    ExtremeValueFit,
    FatigueDamageResult,
    Peak,
    PeakResult,
    RainflowCycle,
    RainflowResult,
    SNCurve,
    StatisticsResult,
    calculate_del,
    calculate_fatigue_damage,
    compute_statistics,
    count_rainflow,
    extract_peaks,
    fit_extreme_distribution,
    return_period_response,
)
from offshoresafe.project import (
    AnalysisConfiguration,
    OffshoreProject,
    ProjectInformation,
    SolverInformation,
    TurbineInformation,
    load_project,
    save_project,
)
from offshoresafe.solver import (
    HEROWINDAdapter,
    OpenFASTAdapter,
    SolverAdapter,
    SolverCapability,
    SolverResult,
)

__all__ = [
    "AnalysisConfiguration",
    "ChannelStatistics",
    "ExtremeValueFit",
    "FatigueDamageResult",
    "HEROWINDAdapter",
    "OffshoreProject",
    "OpenFASTAdapter",
    "Peak",
    "PeakResult",
    "ProjectInformation",
    "RainflowCycle",
    "RainflowResult",
    "SNCurve",
    "SolverAdapter",
    "SolverCapability",
    "SolverInformation",
    "SolverResult",
    "StatisticsResult",
    "TurbineInformation",
    "__version__",
    "calculate_del",
    "calculate_fatigue_damage",
    "compute_statistics",
    "count_rainflow",
    "extract_peaks",
    "fit_extreme_distribution",
    "load_project",
    "return_period_response",
    "save_project",
]
